dist: xenial
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq postfix
before_script:
  - sudo service postfix stop
  - smtp-sink -d test-mail localhost:2500 20 &
script:
  - RENEWED_DOMAINS="foo.bar ham.cheese" RENEWED_LINEAGE=`pwd` ./certbot_notify_post_hook.py --print-only test@test.invalid dummy@dummy.invalid
  - RENEWED_DOMAINS="foo.bar ham.cheese" RENEWED_LINEAGE=`pwd` ./certbot_notify_post_hook.py --smtp-port=2500 test@test.invalid dummy@dummy.invalid